version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.6
  build:
    commands:
      - export BUCKET=charles-lambda-hello-world
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
